user http; 
worker_processes  auto; #1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    # Remove cacheing to disable "304 Not Modified" response, convenient for testing...
    add_header Cache-Control no-cache;
    if_modified_since off;
    add_header Last-Modified "";

    #gzip  on;

    index index.html index.htm build/index.html;

    server {
        server_name  riyadshauk.com;
   	root /var/www/riyadshauk.com/build;
#	root /var/www;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

	location / {
		add_header "riyad-section" "/";
		add_header "riyad-uri" "$uri";
		if (!-e $request_filename) {
			rewrite ^(.*)$ /index.html break;
		}
	}

	location /chess {
		alias /var/www/chess/public;
		try_files $uri $uri/ /$uri /index.html;
	}

	location /photos {
		alias /var/www/family-photos-client/build;
		try_files $uri $uri/ /$uri /index.html;
	}

	location /digital-assistant {
		alias /var/www/oracle-digital-assistant-flow-js/builder-web-app/build;
		try_files $uri $uri/ /$uri /index.html;
	}

	location /photosapi {
     	    	proxy_pass http://127.0.0.1:8081;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header Connection 'upgrade';
  	    proxy_set_header Host $host;
    	    proxy_cache_bypass $http_upgrade;
        }

	location /tmpapi {
		proxy_pass http://127.0.0.1:8000;
#		alias /var/www/movie_app-1.0.0
#		try_files $uri $uri/ =404;
#		proxy_http_version 1.1;
#		proxy_set_header Upgrade $http_upgrade;
#		proxy_set_header Connection 'upgrade';
#		proxy_set_header Host $host;
#		proxy_cache_bypass $http_upgrade;
	}

	location =/resume.pdf {
		root /var/www/riyadshauk.com/public/;
		open_file_cache off;
		expires -1;
		sendfile off;
	}

	# enable browser caching for some static files
#	location ~*  \.(jpg|jpeg|png|gif|ico)$ {
#		expires 7d;
#	}

	#error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

    
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/riyadshauk.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/riyadshauk.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

    server {
    if ($host = riyadshauk.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen       80;
        server_name  riyadshauk.com;
    return 404; # managed by Certbot


}}
